# Generated by Django 5.0.6 on 2024-05-08 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='fecha_creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
